// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_unix.go

package gfapi

type Statvfs_t struct {
	Bsize   uint64
	Frsize  uint64
	Blocks  uint32
	Bfree   uint32
	Bavail  uint32
	Files   uint32
	Ffree   uint32
	Favail  uint32
	Fsid    uint64
	Flag    uint64
	Namemax uint64
}
